const actionTypes = {
    CREATE_USERS_REQUESTED: 'CREATE_USERS_REQUESTED',
    CREATE_USERS_SUCCESS: 'CREATE_USERS_SUCCESS',
    CREATE_USERS_FAILED: 'CREATE_USERS_FAILED',


    SIGNIN_USERS_REQUESTED: 'SIGNIN_USERS_REQUESTED',
    SIGNIN_USERS_SUCCESS: 'SIGNIN_USERS_SUCCESS',
    SIGNIN_USERS_FAILED: 'SIGNIN_USERS_FAILED',

  };
  
  export default actionTypes;